---
title: "Likoaeng Preliminary Results"
execute: 
  echo: false
  warning: false
  message: false
format: docx
editor: visual
---

```{r library}
#| warning: false
#| message: false

# To plot figures

library(ggplot2)
library(forcats)
library(ggpubr)
library(ggridges)
library(cowplot)
library(ggforce)

library(infer)
#library(rcompanion)
library(purrr)
library(modelr)
#library(rcompanion)
library(viridis)

library(scales)
library(stringr)

# To generate tables
library(gtsummary)
library(gt)
library(broom)
library(broom.mixed)

library(stargazer)
library(kableExtra)

# To tidy the data
library(tidyr)
library(tidyverse)
library(dplyr)
library(forcats)
library(here)
library(tidybayes)

# Bayesian models
library(brms)
library(emmeans)
library(loo)
library(BayesFactor)
library(posterior)

```

```{r}
#| message: false
#| warning: false

# Read and clean the data
dir = here::here()

df_24 <- read_csv(paste0(dir, "/data/AG_Winter2024_LIK_Final.csv"))
df_25 <- read_csv(paste0(dir, "/data/AG_Summer2025_LIK_Final.csv")) |>
  mutate(MASS = as.numeric(MASS)) |>
  select(-"...72")

df_ratios <- read_csv(paste0(dir, "/data/LIK_RiverTerr_Ratios.csv")) |>
  rename("STRAT" = "Strat")

# Merge dataframes
df_raw <- rbind(df_24, df_25) |>
  
  filter(STRAT != "?",
         RAWMATERIAL %in% c("Opaline/CCS", "Hornfels", 
                            "Tuff", "Siltstone")) |>
  
  mutate(STRAT = factor(ifelse(STRAT %in% 
                          c("VII", "VIII", "IX"), "VII/IX", STRAT)),
         STRAT = fct_relevel(STRAT, 
                        c("I", "III", "IV", "V", "VI", "VII/IX", "X",
                          "XI", "XII", "XIII", "XIV", "XV", "XVI",
                          "XVII")),
         
         CORTEX = ifelse(CORTEX == "10-40%", "11-40%",
                  ifelse(CORTEX == "40-60%", "41-60%",
                  ifelse(CORTEX == "60-90%", "61-90%",
                  ifelse(CORTEX == "90-99%", "91-99%", CORTEX)))),
         buckets = ifelse(STRAT == "I", 366,
                   ifelse(STRAT == "III", 416,
                   ifelse(STRAT == "IV", 27.25,
                   ifelse(STRAT == "V", 223.75,
                   ifelse(STRAT == "VI", 289.33,
                   ifelse(STRAT == "VII/IX", 341,
                   ifelse(STRAT == "X", 47.25,
                   ifelse(STRAT == "XI", 69.25,
                   ifelse(STRAT == "XII", 33,
                   ifelse(STRAT == "XIII", 218.67,
                   ifelse(STRAT == "XIV", 26,
                   ifelse(STRAT == "XV", 27.5,
                   ifelse(STRAT == "XVI", 35.25,
                   ifelse(STRAT == "XVII", 18.33,
                          NA)))))))))))))))


df <- df_raw |>
  filter(RAWMATERIAL %in% c("Opaline/CCS", "Hornfels"),
         (STRAT != "X" & STRAT != "XII" & STRAT != "IV")) |>
  full_join(df_ratios) |>
  mutate(fish_dens = (Fish_mass/100)/Volume_m3,
         mammal_dens = (NonFish_mass/100)/Volume_m3,
         STRAT_mod = round(fish_dens/mammal_dens, 2),
         STRAT = factor(STRAT),
         STRAT = droplevels(STRAT)) |>
  drop_na(RAWMATERIAL)


# take average core flake scar length
df |>
  dplyr::filter(ARTIFACTCLASS=="Core") |>
  group_by(RAWMATERIAL)|>
  dplyr::summarise(a = 
                     mean(LENGHTLONGESTFLAKESCAR)) -> df.core_average



# take average core flake scar length
df |>
  dplyr::filter(ARTIFACTCLASS=="Core") |>
  group_by(RAWMATERIAL, STRAT) |>
  summarize(Ave_FlakeLength = mean(LENGHTLONGESTFLAKESCAR)) -> core_size


# set values for small, medium, and large slug effect sizes
small <- 5.18


# Subset data by flakes and flake variables
core_bind <- full_join(core_size, df) |>
  filter(ARTIFACTCLASS == "Flake" & COMPLETENESS == "Complete") |>
  group_by(RAWMATERIAL, STRAT) |>
  mutate(Utility_small = TECHLENGTH*(TECHLENGTH - small),
         
         Transport_small = Utility_small/((MAXTHICKNESS/TECHLENGTH)*TECHLENGTH^3),
         
         Reduction = TECHLENGTH/Ave_FlakeLength) -> df_flakes

# Subset data by cores and core variables
df_cores <- df |>
  filter(ARTIFACTCLASS == "Core" & CORECOMPLETENESS == "Complete") |>
  mutate(SA_Ellipse = (4*pi)*
           ((((((MAXLENGTH/2)*(MAXWIDTH/2))^1.6075)+
           (((MAXLENGTH/2)*(MAXTHICKNESS/2))^1.6075)+
           (((MAXWIDTH/2)+(MAXTHICKNESS/2))^1.6075))/3)^(1/1.6075)))

# Subset data by retouch and retouch variables
df_retouch <- df |>
  filter(ARTIFACTCLASS == "RetouchedTool" & RAWMATERIAL != "BWA UPPER 1" &
           COMPLETENESS == "Complete") |>
  mutate(Utility_small = TECHLENGTH*(TECHLENGTH - small),
         
         Transport_small = Utility_small/((MAXTHICKNESS/TECHLENGTH)*TECHLENGTH^3))
```

## Raw material distribution

```{r tab1}
#| label: tab-one


# Create summary table

df |>
  mutate(across(where(is.factor), droplevels)) |>
  select(STRAT, RAWMATERIAL, ARTIFACTCLASS) |>
  mutate(ARTIFACTCLASS = ifelse(ARTIFACTCLASS ==
                                  "RetouchedTool", "Retouched tools", 
                                ARTIFACTCLASS),
         RAWMATERIAL = 
           fct_relevel(RAWMATERIAL,
                       "Opaline/CCS", "Hornfels", "Tuff")) |>
  rename(Layer = STRAT,
         `Artifact class` = ARTIFACTCLASS) |>
  filter(RAWMATERIAL %in% c("Opaline/CCS", "Hornfels", "Tuff")) |>
  tbl_strata(
    strata = RAWMATERIAL,
    .tbl_fun =
      ~ .x |>
        tbl_summary(by = "Artifact class", missing = "no") |> add_n()
  ) |>
  modify_header(label = "") -> tab1
tab1

#gtsave(tab1, "Table1.png")
```

```{r}
#| message: false
#| warning: false

# coastal diets
df |>
  group_by(STRAT_mod, RAWMATERIAL) |>
  summarize(Freq = n()) |>
  mutate(cs = sum(Freq),
         prop = Freq/cs) |>
  ggplot(aes(x = factor(STRAT_mod, ordered = T), y = prop, fill = RAWMATERIAL))+
  geom_col()+
  labs(fill = "",
       x = "Fish-to-Mammal",
       y = "Proportion") +
  theme_minimal()+
  theme_classic(base_size = 18)+
  scale_fill_viridis_d()+
  theme(axis.text.x = 
          element_text(angle = 45, hjust = 1)) -> RM_plot00
```

```{r}
png("../results/figures/fig8.png", width = 290, height = 120,
    units = "mm", res = 300)

ggarrange(
  RM_plot00,
  align = "h",
  common.legend = TRUE
)

dev.off()

```

```{r Dirchlet_Prop_Ind0}
fit_df <- df |>
  mutate(STRAT_mod = factor(STRAT_mod))

# Bayesian test
my_prior <- 
  prior(normal(0, 1.5), class = "Intercept") +
  prior(exponential(1), class = "sd")  

cat1 <- brm(
  RAWMATERIAL ~ 1 + (1|STRAT_mod),
  family = bernoulli(),
  data = fit_df,
  prior = my_prior,
  iter = 4000,
  seed = 77644123,
  chains = 4,
  save_pars = save_pars(all = TRUE),
  cores = getOption("mc.cores", parallel::detectCores())
)

newdat <- expand.grid(
  STRAT_mod = unique(fit_df$STRAT_mod)
)

props <- cat1 |>
  epred_draws(
    newdata = newdat,
    re_formula = NULL   # include strat-level random effects
  ) |>
  group_by(STRAT_mod) |>
  summarise(
    mean = mean(.epred),
    l95  = quantile(.epred, 0.05),
    u95  = quantile(.epred, 0.95),
    .groups = "drop"
  )




cat2 <- brm(
  RAWMATERIAL ~ STRAT_mod,
  family = bernoulli(),
  data = fit_df,
  iter = 4000,
  seed = 7764412300000,
  chains = 4,
  save_pars = save_pars(all = TRUE),
  cores = getOption("mc.cores", parallel::detectCores())
)


pws_tmp <- pairs(emmeans(cat2,
         specs = "STRAT_mod",
         type = "response"))

df_tmp <- summary(pws_tmp, infer = TRUE)
write.csv(file = paste0(dir,"/results/tables/", "RawMaterial_Prop_pairwise.csv"), 
                        x = as.data.frame(df_tmp))

```

```{r}
# posterior comparison
pp <- fit_df |>
  add_epred_draws(cat1, ndraws = 500) |> 
  group_by(.draw, STRAT_mod) |>
  summarise(prob = mean(.epred), .groups = "drop") |>
  pivot_wider(names_from = STRAT_mod, values_from = prob)


z = 1
mat = matrix(nrow = length(names(pp)),
             ncol = length(names(pp)))
t = tibble('draw' = numeric(),
           'diff' = numeric(),
           'cat' = character())
for(n in 1:nrow(pp)){
  for(i in names(pp)[-1]){
    for(j in names(pp)[-1]){
      t[z, 'diff'] = pp[n, paste0(i)] - pp[n, paste0(j)]
      t[z, 'draw'] = n
      t[z, 'cat'] = paste0(i, "-", j)
      z = z + 1
    }
  }
}

pwise <- t |>
  group_by(cat) |>
   summarise(mean = mean(diff), 
             lwr = quantile(diff, probs = 0.05),
             upr = quantile(diff, probs = 0.95))

```

```{r RMGGplot}
#| message: false
#| warning: false

df |>
  group_by(STRAT_mod, RAWMATERIAL, ARTIFACTCLASS) |>
  summarize(Freq = n()) |>
  mutate(cs = sum(Freq),
         prop = Freq/cs) |>
  ggplot(aes(x = factor(STRAT_mod, ordered = T), y = prop, fill = ARTIFACTCLASS))+
  geom_col()+
  facet_wrap(~RAWMATERIAL)+
  labs(fill = "",
       x = "Fish-to-Mammal",
       y = "Proportion") +
  scale_fill_viridis_d()+
  theme_minimal()+
  theme_classic(base_size = 18)+
  theme(axis.text.x = 
          element_text(angle = 45, hjust = 1)) -> RM_plot2

```

```{r fig-Figure5}

png("../results/figures/fig9.png", width = 290, height = 120,
    units = "mm", res = 300)

ggarrange(
  RM_plot2,
  align = "h",
  common.legend = TRUE
)

dev.off()

```

```{r Dirchlet_Prop_Individual}
# Bayesian test
K <- 3 # Number of classes
delta = 0.0001

dir <- df |>
  group_by(RAWMATERIAL, ARTIFACTCLASS, STRAT_mod) |>
  count() |>
  pivot_wider(names_from = ARTIFACTCLASS, values_from = n, values_fill = 0) |>
  mutate(total = Core + Flake + RetouchedTool,
         
         Core_prop = Core/total,
         Flake_prop = Flake/total,
         RetouchedTool_prop = RetouchedTool/total,
         
         # Apply a negligible offset to account for 0 probabilities
         Core_propK = (Core + delta) / (total + K*delta),
         Flake_propK = (Flake + delta) / (total + K*delta),
         RetouchedTool_propK = (RetouchedTool + delta) / (total + K*delta),
         
         y = cbind(Core_propK, Flake_propK, RetouchedTool_propK)
         ) |>
  select(RAWMATERIAL, STRAT_mod,
         Core_prop, Core_propK,
         Flake_prop, Flake_propK,
         RetouchedTool_prop, RetouchedTool_propK,
         y)


fit_df_dmi <- df |>
  mutate(STRAT_mod = scale(STRAT_mod))

my_prior <- 
  prior(normal(0.5, 1), class = "Intercept")+
  prior(normal(0.5, 1), class = "b")

bayes_dmi <- brm(
  RAWMATERIAL ~ ARTIFACTCLASS*STRAT_mod,
  family = bernoulli(),
  data = fit_df_dmi,
  prior = my_prior,
  iter = 4000,
  seed = 818777830,
  chains = 4,
  save_pars = save_pars(all = TRUE),
  cores = getOption("mc.cores", parallel::detectCores())
)


newdat <- expand.grid(
  STRAT_mod = seq(min(fit_df_dmi$STRAT_mod),
                  max(fit_df_dmi$STRAT_mod),
                  length = 100),
  ARTIFACTCLASS = unique(fit_df_dmi$ARTIFACTCLASS)
)

epred_draws(bayes_dmi, newdata = newdat) |>
  group_by(ARTIFACTCLASS) |>
  summarize(median = mean(.epred),
            upr = quantile(.epred, 0.95),
            lwr = quantile(.epred, 0.05))

post <- as_draws(bayes_dmi)
(mean(post$`1`$b_STRAT_mod > 0) + mean(post$`2`$b_STRAT_mod > 0) +
  mean(post$`3`$b_STRAT_mod > 0) + mean(post$`4`$b_STRAT_mod > 0)) / 4

```

## Surplus

```{r AllMass}
# design model to look at the relationship between artifact mass and the 50th and 75th percentiles
# filter by values that caused errors in the models
fit_df <- df |>
      group_by(RAWMATERIAL) |>
      filter( MASS > 0, MASS < 500) |>
      mutate(log_MASS = log(MASS),
             STRAT_mod_s = as.numeric(scale(STRAT_mod, center = T, scale = T)),
         STRAT_mod = factor(STRAT_mod)) |>
  select(RAWMATERIAL, STRAT_mod, STRAT_mod_s, MASS)

# Gamma prior for individual layers and Mass
Gamma_Prior_Mass_Ind <- 
  prior(normal(0, 0.5), class = "Intercept")+
  prior(normal(1, 0.5), class = "b", coef = "RAWMATERIALOpalineDCCS")+
  
  prior(normal(0, 1), class = "b", coef = "STRAT_mod_s")+ 
  prior(normal(1, 0.5), class = "b", coef = "STRAT_mod_s:RAWMATERIALOpalineDCCS")+
  
  prior(gamma(2, 0.5), class = "shape")


Gamma_Prior_Mass_All <- 
  prior(normal(0, 0.5), class = "Intercept")+
  prior(normal(1, 0.5), class = "b", coef = "RAWMATERIALOpalineDCCS")+
  
  prior(normal(0.5, 0.5), class = "b", coef = "STRAT_mod0.09")+
  prior(normal(0.5, 0.5), class = "b", coef = "STRAT_mod0.1")+
  prior(normal(0.5, 0.5), class = "b", coef = "STRAT_mod0.2")+
  prior(normal(0.5, 0.5), class = "b", coef = "STRAT_mod0.3")+
  prior(normal(0.5, 0.5), class = "b", coef = "STRAT_mod0.82")+
  prior(normal(0.5, 0.5), class = "b", coef = "STRAT_mod1.08")+
  prior(normal(1, 0.5), class = "b", coef = "STRAT_mod1.44")+
  prior(normal(1, 0.5), class = "b", coef = "STRAT_mod2.15")+
  prior(normal(1, 0.5), class = "b", coef = "STRAT_mod2.88")+
  prior(normal(1, 0.5), class = "b", coef = "STRAT_mod3.37")+
  
  prior(gamma(2, 0.5), class = "shape")
```

```{r fitAllMass}
fit_mass_all_ind <- brm(
  MASS ~ STRAT_mod_s*RAWMATERIAL,
  data = fit_df,
  family = Gamma(link = "log"),
  prior = Gamma_Prior_Mass_Ind,
  cores = getOption("mc.cores", parallel::detectCores()),
  chains = 4,
  iter = 4000,
  seed = 2325778
)


fit_mass_all_phase <- brm(
  MASS ~ STRAT_mod*RAWMATERIAL,
  data = fit_df,
  family = Gamma(link = "log"),
  prior = Gamma_Prior_Mass_All,
  cores = getOption("mc.cores", parallel::detectCores()),
  chains = 4,
  iter = 4000,
  seed = 20000008
)

```

```{r}
#| include: false
#| warning: false
#| message: false


# Posterior checks for individual data

pp_check(fit_mass_all_ind, type = "dens_overlay_grouped",
         group = "STRAT_mod_s")
pp_check(fit_mass_all_ind, type = "stat_grouped", 
         group = "STRAT_mod_s")
pp_check(fit_mass_all_ind, type = "scatter_avg_grouped",
         group = "STRAT_mod_s")

pp_check(fit_mass_all_ind, type = "dens_overlay_grouped", 
         group = "RAWMATERIAL")
pp_check(fit_mass_all_ind, type = "stat_grouped", 
         group = "RAWMATERIAL")
pp_check(fit_mass_all_ind, type = "scatter_avg_grouped",
         group = "RAWMATERIAL")

loo1 <- loo(fit_mass_all_ind, moment_match = T)
plot(loo1)
```

```{r}
new_data <- expand.grid(
  STRAT_mod_s = seq(min(fit_df$STRAT_mod_s),
                  max(fit_df$STRAT_mod_s), length.out = 100),
  RAWMATERIAL = unique(fit_df$RAWMATERIAL)
)


fit_df |>
  group_by(RAWMATERIAL) |>
  add_epred_draws(fit_mass_all_ind) |>
  median_qi(.epred, .width = 0.9) |>
  
  ggplot(aes(x = STRAT_mod_s, y = .epred,
             color = RAWMATERIAL, fill = RAWMATERIAL)) +
  geom_line(size = 1)  +
  geom_ribbon(aes(ymin = .lower, ymax = .upper),
              alpha = 0.2, color = NA) +
  scale_fill_viridis_d() +
  scale_color_viridis_d() +
  scale_y_continuous("Posterior Median Artifact Mass") +
  labs(x = "Mammal → Fish (Standardized)") +
  theme_classic(base_size = 18)+
  guides(fill = guide_legend(title = NULL),
         color = guide_legend(title = NULL))-> Mass_plot1


####################################
median <- fit_df |>
  group_by(RAWMATERIAL) |>
  summarize(median = quantile(MASS, prob = 0.5),
            upr = quantile(MASS, prob = 0.75))
  
  
  
fit_mass_all_phase |>
  epred_draws(
    newdata = distinct(fit_df, STRAT_mod, RAWMATERIAL)
    ) |>
  ggplot() +
  stat_halfeye(aes(x = STRAT_mod, y = .epred),
               .width = c(.90, .5), scale = 0, linewidth = 1, point_size = 0.7,
               adjust = 0.8, width = 0.6,
               orientation = "vertical", point_interval = "median_qi")+
  geom_hline(data = median, aes(yintercept = median), color = "red")+
  geom_hline(data = median, aes(yintercept = upr), color = "forestgreen", lty = 2)+
  facet_wrap(~RAWMATERIAL, scales = "free") +
  theme_minimal()+
  theme(legend.title = element_blank())+
  theme_classic(base_size = 18)+
  guides(color = "none")+
    theme(axis.text.x = 
          element_text(angle = 45, hjust = 1),
          text = element_text(size = 18),
          legend.position = "none") +
  ylab("Posterior Median Artifact Mass") + xlab("Fish-to-Mammal") -> Mass_plot2

# Pairwise comparison
pws_tmp <- pairs(emmeans(fit_mass_all_phase, ~ STRAT_mod | RAWMATERIAL), 
      level = 0.90, adjust = "tukey")

df_tmp <- summary(pws_tmp, infer = TRUE)
write.csv(file = paste0(dir, "/results/tables/", "Surplus_pairwise.csv"),
          x = as.data.frame(df_tmp))

# Test hypothesis that slopes greater than 0
posterior <- as_draws(fit_mass_all_ind)$`1` # get posterior draws

mean(posterior$b_STRAT_mod_s > 0)
mean(posterior$b_STRAT_mod_s+posterior$`b_STRAT_mod_s:RAWMATERIALOpalineDCCS` > 0)
```

```{r}
png("../results/figures/fig14.png", width = 290, height = 220,
    units = "mm", res = 300)

ggarrange(
  Mass_plot2, Mass_plot1, nrow = 2,
  font.label = list(size = 25, face = "bold"),
  common.legend = FALSE, labels = c("A", "B"),
  widths = c(2, 1), heights = c(1.5, 1),
  label.y = c(0.98, 1.2),
  label.x = c(0.03, 0.03)
)

dev.off()
```
