---
title: "Untitled"
format: html
editor: visual
---

```{r library}
#| warning: false
#| message: false


# To plot figures
library(ggplot2)
library(forcats)
library(ggpubr)
library(ggridges)
library(cowplot)
library(ggforce)

library(infer)
#library(rcompanion)
library(purrr)
#library(rcompanion)
library(viridis)

library(scales)
library(stringr)

# To generate tables
library(gtsummary)
library(gt)
library(broom)
library(broom.mixed)

library(stargazer)
library(kableExtra)

# To tidy the data
library(tidyr)
library(tidyverse)
library(dplyr)
library(forcats)
library(tidybayes)
library(here)

# Bayesian models
library(brms)
library(emmeans)
library(loo)
library(BayesFactor)
library(posterior)
```

```{r ScraperRetouchFormula}
# Calculate scraper retouch intensity
scraper_red <- function(L, D, a, b){
  
  t = D * sin(a)
  D3 = D * cos(a)
  D1 = t/(sin(b))
  D4 = (t * cos(b))/(sin(b))
  
  D2 = D4 - D3
  
  B = t * (sin(b)) # define base B to find height (which is also D1)
  
  h = sin(b) * ((t*(cos(b)/sin(b))) - (D*cos(a)))
  
  A =  0.5 * B * h# find values of area now
  
  RE = L*((D^2)/2)*((sin(a*(pi/180))^2 * 
                       (cos(b*(pi/180))/sin(b*(pi/180)))) - 
                      (sin(a*(pi/180)) * cos(a*(pi/180))))
  
  
  output <- tibble(Reduction = RE)
  
  return(output)
  
  
}
```

```{r ReadData}
#| message: false
#| warning: false

# Read and clean the data
dir = here::here()

df_24 <- read_csv(paste0(dir, "/data/AG_Winter2024_LIK_Final.csv"))
df_25 <- read_csv(paste0(dir, "/data/AG_Summer2025_LIK_Final.csv")) |>
  mutate(MASS = as.numeric(MASS)) |>
  select(-"...72")

df_ratios <- read_csv(paste0(dir, "/data/LIK_RiverTerr_Ratios.csv")) |>
  rename("STRAT" = "Strat")

# Merge dataframes
df_raw <- rbind(df_24, df_25) |>
  
  filter(STRAT != "?",
         RAWMATERIAL %in% c("Opaline/CCS", "Hornfels", 
                            "Tuff", "Siltstone")) |>
  
  mutate(STRAT = factor(ifelse(STRAT %in% 
                          c("VII", "VIII", "IX"), "VII/IX", STRAT)),
         STRAT = fct_relevel(STRAT, 
                        c("I", "III", "IV", "V", "VI", "VII/IX", "X",
                          "XI", "XII", "XIII", "XIV", "XV", "XVI",
                          "XVII")),
         
         CORTEX = ifelse(CORTEX == "10-40%", "11-40%",
                  ifelse(CORTEX == "40-60%", "41-60%",
                  ifelse(CORTEX == "60-90%", "61-90%",
                  ifelse(CORTEX == "90-99%", "91-99%", CORTEX)))),
         buckets = ifelse(STRAT == "I", 366,
                   ifelse(STRAT == "III", 416,
                   ifelse(STRAT == "IV", 27.25,
                   ifelse(STRAT == "V", 223.75,
                   ifelse(STRAT == "VI", 289.33,
                   ifelse(STRAT == "VII/IX", 341,
                   ifelse(STRAT == "X", 47.25,
                   ifelse(STRAT == "XI", 69.25,
                   ifelse(STRAT == "XII", 33,
                   ifelse(STRAT == "XIII", 218.67,
                   ifelse(STRAT == "XIV", 26,
                   ifelse(STRAT == "XV", 27.5,
                   ifelse(STRAT == "XVI", 35.25,
                   ifelse(STRAT == "XVII", 18.33,
                          NA)))))))))))))))


df <- df_raw |>
  filter(RAWMATERIAL %in% c("Opaline/CCS", "Hornfels"),
         (STRAT != "X" & STRAT != "XII" & STRAT != "IV")) |>
  full_join(df_ratios) |>
  mutate(fish_dens = (Fish_mass/100)/Volume_m3,
         mammal_dens = (NonFish_mass/100)/Volume_m3,
         STRAT_mod = round(fish_dens/mammal_dens, 2),
         STRAT = factor(STRAT),
         STRAT = droplevels(STRAT)) |>
  drop_na(RAWMATERIAL)


df_raw <- df_raw |>
  filter(RAWMATERIAL %in% c("Opaline/CCS", "Hornfels")) |>
  full_join(df_ratios) |>
  mutate(fish_dens = (Fish_mass/100)/Volume_m3,
         mammal_dens = (NonFish_mass/100)/Volume_m3,
         STRAT_mod = round(fish_dens/mammal_dens, 2),
         STRAT = factor(STRAT),
         STRAT = droplevels(STRAT)) |>
  drop_na(RAWMATERIAL)


# take average core flake scar length
df_raw |>
  dplyr::filter(ARTIFACTCLASS=="Core") |>
  group_by(RAWMATERIAL)|>
  dplyr::summarise(a = 
                     mean(LENGHTLONGESTFLAKESCAR)) -> df.core_average



# take average core flake scar length
df_raw |>
  dplyr::filter(ARTIFACTCLASS=="Core") |>
  group_by(RAWMATERIAL, STRAT) |>
  summarize(Ave_FlakeLength = mean(LENGHTLONGESTFLAKESCAR)) -> core_size


# set values for small, medium, and large slug effect sizes
small <- 5.18


# Subset data by flakes and flake variables
core_bind <- full_join(core_size, df_raw) |>
  filter(ARTIFACTCLASS == "Flake" & COMPLETENESS == "Complete") |>
  group_by(RAWMATERIAL, STRAT) |>
  mutate(Utility_small = TECHLENGTH*(TECHLENGTH - small),
         
         Transport_small = Utility_small/((MAXTHICKNESS/TECHLENGTH)*TECHLENGTH^3),
         
         Reduction = TECHLENGTH/Ave_FlakeLength) -> df_flakes

# Subset data by cores and core variables
df_cores <- df_raw |>
  filter(ARTIFACTCLASS == "Core" & CORECOMPLETENESS == "Complete") |>
  mutate(SA_Ellipse = (4*pi)*
           ((((((MAXLENGTH/2)*(MAXWIDTH/2))^1.6075)+
           (((MAXLENGTH/2)*(MAXTHICKNESS/2))^1.6075)+
           (((MAXWIDTH/2)+(MAXTHICKNESS/2))^1.6075))/3)^(1/1.6075)))

# Subset data by retouch and retouch variables
df_retouch <- df_raw |>
  filter(ARTIFACTCLASS == "RetouchedTool" & RAWMATERIAL != "BWA UPPER 1" &
           COMPLETENESS == "Complete") |>
  mutate(Utility = MAXLENGTH*(MAXLENGTH - small),
         
         Transport = Utility/((MAXTHICKNESS/TECHLENGTH)*TECHLENGTH^3)) 



```

## Scraper Utility to Retouch

```{r scraperRetouchIntensity}
# Define a database for scraper retouch
df_scrap <- df_retouch |>
  filter(COMPLETENESS == "Complete") |>
  filter(RETOUCHEDPIECETYPOLOGY == "SideScraper" | 
           RETOUCHEDPIECETYPOLOGY == "EndScraper" |
           RETOUCHEDPIECETYPOLOGY == "Side-EndScraper") |>
  select("SCRAPERRETOUCHHEIGHT1","SCRAPERRETOUCHHEIGHT2","SCRAPERRETOUCHHEIGHT3",
         "SCRAPERRETOUCHANGLE1","SCRAPERRETOUCHANGLE2","SCRAPERRETOUCHANGLE3",
         "SCRAPERDORSALANGLE1","SCRAPERDORSALANGLE2","SCRAPERDORSALANGLE3",
         "SCRAPERRETOUCHLENGTH","SCRAPERMAXTHICKNESS",
         
         "SCRAPERRETOUCHHEIGHT1", "SCRAPERRETOUCHHEIGHT2", "SCRAPERRETOUCHHEIGHT3",
         
         "MAXLENGTH", "MAXWIDTH",
         
         "RAWMATERIAL", "STRAT", "STRAT_mod", "MASS",
         
         "Utility") |>
  mutate(RET_INT = round(((SCRAPERRETOUCHHEIGHT1+
                            SCRAPERRETOUCHHEIGHT2+
                            SCRAPERRETOUCHHEIGHT3)/SCRAPERMAXTHICKNESS)*
                           SCRAPERRETOUCHLENGTH,2),
         SA = MAXLENGTH*MAXWIDTH)


# Preprocess data to enter into custom function to calculate scraper reduction
scrap_red <- df_scrap |>
  mutate(D = (SCRAPERRETOUCHHEIGHT1+SCRAPERRETOUCHHEIGHT2+SCRAPERRETOUCHHEIGHT3)/3,
         a = (SCRAPERRETOUCHANGLE1+SCRAPERRETOUCHANGLE2+SCRAPERRETOUCHANGLE3)/3,
         b = (SCRAPERDORSALANGLE1+SCRAPERDORSALANGLE2+SCRAPERDORSALANGLE3)/3) |>
  rename(L = SCRAPERRETOUCHLENGTH) |>
  mutate(GIUR = scraper_red(L, D, a, b)$Reduction,
         Rem.Weight = MASS,
         Max.thick = SCRAPERMAXTHICKNESS,
         Mean.t = mean(SCRAPERRETOUCHHEIGHT1+
                         SCRAPERRETOUCHHEIGHT2+
                         SCRAPERRETOUCHHEIGHT3),
         ID = 1:n())

# Export for R shiny app
scrap_export <- scrap_red |> 
  mutate() |>
  select(Rem.Weight, Max.thick, Mean.t, GIUR)

write.csv(scrap_export, paste0(dir, "/data/LIK_Scrap_Input.csv"))
```

### Grouped Layers

```{r}
scrap_pred <- read_csv(paste0(dir, "/data/LIK_Scrap_Pred.csv")) |>
  select(`Percent.Consumed`) |>
  mutate(Utility = df_scrap$Utility,
         STRAT_mod = df_scrap$STRAT_mod,
         RAWMATERIAL = df_scrap$RAWMATERIAL
         )|>
  rename(RETOUCH = Percent.Consumed)
```

```{r}
# Refine outliers and define priors and run bayesian model
lm_red <- scrap_pred

lm_red$STRAT_mod_s <- scale(lm_red$STRAT_mod, center = T, scale = T)

fit_df <- lm_red |>
  mutate(Utility_s = Utility/100,
         Reduction_s = RETOUCH/100,
         STRAT_mod = factor(STRAT_mod)) |>
  select(Reduction_s, Utility_s, STRAT_mod, STRAT_mod_s, RAWMATERIAL) |>
  na.omit()

```

##### Nonlinear Models

```{r}
nlform0 <- bf(Utility_s ~ a * exp(-b * Reduction_s),
             a ~ 1, 
             b ~ 1,
             nl = TRUE)

nlform1 <- bf(Utility_s ~ a * exp(-b * Reduction_s),
             a ~ 1 + (1 | STRAT_mod), 
             b ~ 1 + (1 | STRAT_mod),
             nl = TRUE)


nlform3 <- bf(Utility_s ~ a * exp(-b * Reduction_s),
             a ~ 1 + STRAT_mod_s,
             b ~ 1 + STRAT_mod_s,
             nl = TRUE)

priors <- c(
  prior(lognormal(log(1), 0.5), nlpar = "a"),
  prior(lognormal(log(1), 0.5), nlpar = "b"),
  prior(exponential(1), class = "sigma")
)


bayes_prior0 <- brm(nlform0,
              data = fit_df,
              family = lognormal(),
              iter = 2000,
              chains = 2,
              seed = 77779777,
              control = list(adapt_delta = 0.95),
              prior=priors,
              sample_prior = "only",
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))


bayes_prior1 <- brm(nlform1,
              data = fit_df,
              family = lognormal(),
              iter = 2000,
              chains = 2,
              seed = 17770777,
              control = list(adapt_delta = 0.95),
              prior=priors,
              sample_prior = "only",
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))


bayes_prior3 <- brm(nlform3,
              data = fit_df,
              family = lognormal(),
              iter = 2000,
              chains = 2,
              seed = 12223308887,
              control = list(adapt_delta = 0.95),
              prior=priors,
              sample_prior = "only",
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))


bayes_nl0 <- update(bayes_prior0, sample_prior = "no")
bayes_nl1 <- update(bayes_prior1, sample_prior = "no")
bayes_nl3 <- update(bayes_prior3, sample_prior = "no")
```

```{r}
#| include: false
loo_nl0 <- loo(bayes_nl0)
loo_nl1 <- loo(bayes_nl1)
loo_nl3 <- loo(bayes_nl3)

loo_compare(loo_nl0, loo_nl1, loo_nl3)
```

##### Linear Models

```{r}
simple1 <- brm(Utility_s ~ 1,
              data = fit_df,
              family = Gamma(link = "log"),
              iter = 2000,
              chains = 2,
              seed = 111,
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))

simple2 <- brm(Utility_s ~ 1 + Reduction_s,
              data = fit_df,
              family = Gamma(link = "log"),
              iter = 2000,
              chains = 2,
              seed = 1112,
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))

simple3 <- brm(Utility_s ~ 1 + Reduction_s + STRAT_mod,
              data = fit_df,
              family = Gamma(link = "log"),
              iter = 2000,
              chains = 2,
              seed = 1113,
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))

############## POLYNOMIAL ##############
poly1 <- brm(Utility_s ~ 1 + poly(Reduction_s, 2, raw = TRUE),
              data = fit_df,
              family = Gamma(link = "log"),
              iter = 2000,
              chains = 2,
              seed = 1114,
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))

poly2 <- brm(Utility_s ~ 1 + poly(Reduction_s, 2, raw = TRUE) + 
               STRAT_mod,
              data = fit_df,
              family = Gamma(link = "log"),
              iter = 2000,
              chains = 2,
              seed = 1115,
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))


poly5 <- brm(Utility_s ~ 1 + poly(Reduction_s, 2, raw = TRUE)* 
              STRAT_mod,
              data = fit_df,
              family = Gamma(link = "log"),
              iter = 2000,
              chains = 2,
              seed = 21734816,
              control = list(max_treedepth = 12),
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", parallel::detectCores()))

################# MULTILEVEL ####################
multi1 <- brm(Utility_s ~ 1 + poly(Reduction_s, 2, raw = TRUE) +
            (0 + poly(Reduction_s, 2, raw = TRUE) | STRAT_mod),
              data = fit_df,
              family = Gamma(link = "log"),
              iter = 2000,
              chains = 2,
              seed = 1117,
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))

multi2 <- brm(Utility_s ~ 1 + STRAT_mod + poly(Reduction_s, 2, raw = TRUE) +
            (0 + poly(Reduction_s, 2,
                      raw = TRUE) | STRAT_mod),
              data = fit_df,
              family = Gamma(link = "log"),
              iter = 2000,
              chains = 2,
              seed = 1118,
              #prior=my_prior,
              save_pars = save_pars(all = TRUE),
              cores = getOption("mc.cores", 14))


```

```{r}
#| include: false
simple1_loo <- loo(simple1)
simple2_loo <- loo(simple2)
simple3_loo <- loo(simple3)

poly1_loo <- loo(poly1)
poly2_loo <- loo(poly2)
poly5_loo <- loo(poly5)

multi1_loo <- loo(multi1)
multi2_loo <- loo(multi2)

loo_compare(simple1_loo, simple2_loo, simple3_loo,
            poly1_loo, poly2_loo, poly5_loo,
            multi1_loo, multi2_loo,
            
            loo_nl0, loo_nl1, loo_nl3)

# remove all models of lesser fit to save space
remove(list = c("simple1", "simple2", "simple3", "poly1", "poly3",
                "poly2", "poly4", "poly5", "poly6",
                "multi2",
                
                "loo_n10", "loo_nl1", "loo_nl2", "loo_nl3"))
```

```{r}

x_seq <- seq(min(fit_df$Reduction_s, na.rm = TRUE),
             max(fit_df$Reduction_s, na.rm = TRUE),
             length.out = 100)

draws <- as_draws_df(multi1)

# All combinations of grouping levels
slope_draws <- expand_grid(
  draws,
  Reduction_s = x_seq,
  STRAT_mod = unique(fit_df$STRAT_mod)
) |>
  mutate(
    eta = b_Intercept +
          b_polyReduction_s2rawEQTRUE1 * Reduction_s +
          b_polyReduction_s2rawEQTRUE2 * Reduction_s^2,

    slope = exp(eta) *
            (b_polyReduction_s2rawEQTRUE1 +
             2 * b_polyReduction_s2rawEQTRUE2 * Reduction_s)
  )


slope_summary <- slope_draws |>
  group_by(Reduction_s) |>
  summarise(
    mean = mean(slope),
    lwr = quantile(slope, 0.05),
    upr = quantile(slope, 0.95),
    .groups = "drop"
  )


ggplot(slope_summary, aes(Reduction_s, mean)) +
  geom_line(linewidth = 1) +
  geom_ribbon(aes(ymin = lwr, ymax = upr),
              alpha = 0.25) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  labs(
    x = "Reduction_s",
    y = "Marginal slope of Utility",
    title = "Marginal effect of Reduction on Utility"
  ) +
  theme_minimal()



pp <- conditional_effects(
  multi1,
  effects = "Reduction_s",
  re_formula = NA
)

plot(pp, points = TRUE)
```

```{r}
x_seq <- seq(min(fit_df$Reduction_s, na.rm = TRUE),
             max(fit_df$Reduction_s, na.rm = TRUE),
             length.out = 100)

draws <- as_draws_df(multi1)
ranef <- ranef(multi1)$`STRAT_mod`[,,]


groups_to_plot <- fit_df |>
  count(STRAT_mod) |>
  rename("group" = "STRAT_mod") |>
  arrange(desc(n)) |>
  pull(group)



slope_group_draws <- map_dfr(groups_to_plot, function(g) {

  
  g1 <- paste0("r_STRAT_mod[", g, ",polyReduction_s2rawEQTRUE1]")
  g2 <- paste0("r_STRAT_mod[", g, ",polyReduction_s2rawEQTRUE2]")

  expand_grid(
    draws,
    Reduction_s = x_seq
  ) |>
    mutate(
      group = g,

      b1g = b_polyReduction_s2rawEQTRUE1 + .data[[g1]],
      b2g = b_polyReduction_s2rawEQTRUE2 + .data[[g2]],

      eta = b_Intercept +
            b1g * Reduction_s +
            b2g * Reduction_s^2,

      slope = exp(eta) * (b1g + 2 * b2g * Reduction_s)
    )
})


slope_group_summary <- slope_group_draws |>
  group_by(group, Reduction_s) |>
  summarise(
    mean = mean(slope),
    lwr = quantile(slope, 0.05),
    upr = quantile(slope, 0.95),
    .groups = "drop"
  )

png(paste0(dir,"/results/figures/fig17a.png"), width = 290, height = 220,
    units = "mm", res = 300)


ggplot(slope_group_summary,
       aes(Reduction_s, mean)) +
  geom_line(linewidth = 1) +
  geom_ribbon(aes(ymin = lwr, ymax = upr),
              alpha = 0.25) +
  geom_hline(yintercept = 0, linetype = "dashed") +
  facet_wrap(~ group, scales = "free_y") +
  labs(
    x = "Reduction (Scaled)",
    y = expression(Delta~"Utility-to-Reduction")
  ) +
  theme_minimal()

dev.off()
```

```{r}
# Probability slopes are greater than 0
negative_prob <- slope_group_draws |>
  group_by(group, Reduction_s) |>
  summarise(
    Pr_negative = mean(slope < 0),
    .groups = "drop"
  ) |> 
  
  filter(Pr_negative > 0.89) |>
  group_by(group) |>
  summarize(max = max(Reduction_s))

#negative_prob

# Expected slope for each strat at specified reduction value
em_slopes_resp <- emtrends(
  multi1,
  ~ STRAT_mod,
  var = "Reduction_s",
  # Compute from the minimum significant slope for all strats
  at = list(Reduction_s = c(min(negative_prob$max))),
  type = "response",
  allow_new_levels = TRUE,
  re_formula = NULL,
  level = 0.9
)

png(paste0(dir,"/results/figures/fig17b.png"), width = 290, height = 220,
    units = "mm", res = 300)

plot(em_slopes_resp)+
  xlab(expression(Delta*"Utility-to-Reduction"))+
  ylab("Ratio")

dev.off()

pws_tmp <- pairs(em_slopes_resp)
df_tmp <- summary(pws_tmp, infer = TRUE)
write.csv(file = paste0(dir, "/results/tables/",
                        "scraper_utility_retouch_pairwise.csv"), 
          x = as.data.frame(df_tmp))

```

```{r}
# Expected Utility for each strat at specified reduction value
em_slopes_resp <- emmeans(
  multi1,
  ~ STRAT_mod,
  var = "Reduction_s",
  # Compute from the minimum significant slope for all strats
  at = list(Reduction_s = c(min(negative_prob$max))),
  type = "response",
  allow_new_levels = TRUE,
  re_formula = NULL,
  level = 0.9
)
#plot(em_slopes_resp)
#pairs(em_slopes_resp)
```
